WebApplicationNetCore/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationNetCore.Controllers
{
    public class ContactController : Controller
    {

        public ContactController()
        {

        }

        //get: /contact/
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplicationNetCore/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationNetCore.Interfaces;
using WebApplicationNetCore.Models;
using WebApplicationNetCore.Repositories;
using WebApplicationNetCore.ViewModels;
    

namespace WebApplicationNetCore.Controllers
{
    public class PieController : BaseController
    {

        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        //automatically injected by startup.cs  --> ConfigureServices
        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
            ViewData["DomainName"] = "Pie Shop";
        }


        public IActionResult Index()
        {
            ViewBag.Message = "Welcome to Bethany's Pie Shop";
            var pies = _pieRepository.GetPiesOfTheWeek();
            return View(pies);
        }

        public ViewResult List(int? id)
        {

            PieViewModel viewModel = new PieViewModel();
            viewModel.Categories = _categoryRepository.GetAllCategories().ToList();
            if (id.HasValue)
            {
                viewModel.CurrentCategory = _categoryRepository.GetCategoryById(id.Value);
                viewModel.Pies = _pieRepository.GetAllPies().Where(p => p.CategoryId == id.Value).ToList();
            }
            else
            {
                viewModel.Pies = _pieRepository.GetAllPies().ToList();
            }

            return View(viewModel);
        }


        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();

            Pie model = _pieRepository.GetPieById(id.Value);
            if(model==null)
                return NotFound();

            return View(model);
        }
    }
}

WebApplicationNetCore/Views/Shared/_Carousel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="..." alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

WebApplicationNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="it-it">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ViewData["DomainName"]</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("Head", required: false)

</head>
<body>
    <header>
        @*@Html.Partial("_Navbar")*@
        <partial name="_Navbar" />

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @ViewData["DomainName"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)

</body>
</html>

WebApplicationNetCore/Views/Shared/_Navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            @ViewData["DomainName"]
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />

            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Pie" asp-action="Index">Pie Shop</a>
            </li>*@

                @await Component.InvokeAsync("CategoryMenu")

                @await Component.InvokeAsync("ShoppingCartSummary")

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>



            </ul>



        </div>
    </div>
</nav>

WebApplicationNetCore/Views/Shared/_PieCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Pie

@{

}


<div class="col-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="@Model.Name" />
        <div class="caption">
            <p>
                @Model.Category.CategoryName
            </p>
            <h3 class="float-right">@string.Format("{0:c2}", Model.Price)</h3>
            <h3>
                @if (Model.IsPieOfTheWeek)
                {
                    <i class="fas fa-star text-warning" title="Pie of the week"></i>
                }
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>
                @Model.ShortDescription
            </p>

        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="Shoppingcart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.PieId" >Add to cart</a>
            </p>
        </div>
    </div>
</div>