WebApplicationNetCore/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationNetCore.Interfaces;
using WebApplicationNetCore.Models;
using WebApplicationNetCore.ViewModels;

namespace WebApplicationNetCore.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly IPieRepository _pieRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart)
        {
            _pieRepository = pieRepository;
            _shoppingCart = shoppingCart;
            ViewData["DomainName"] = "Pie Shop";
        }

        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var viewModel = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(viewModel);
        }


        public RedirectToActionResult AddToShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);
            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie,1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);
            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }


    }
}

WebApplicationNetCore/Views/Shared/Components/ShoppingCartSummary/Default.cshtml
@model ShoppingCartViewModel

@if(Model.ShoppingCart.ShoppingCartItems.Count > 0)
            {
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
        <i class="fas fa-shopping-cart"></i>
        <span id="cart-status">
            @Model.ShoppingCart.ShoppingCartItems.Count
        </span>
    </a>
</li>
            }